### ISSUE TITLE
Rails 6.0.0.rc1 Support

### ISSUE THREAD

**Issue by tiagocassio** [IcaliaLabs/pager-api#31] opened 2019-04-29 16:51 UTC
Hi, im getting this warning when start Rails server with "rails s":

> DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

I'm using Rails 6.0.0.rc1, pager_api 0.2.4 and kaminari 1.1.1

Thanks!

**Comment by kurenn** [comment] 2019-04-30 23:29
I'm not able to reproduce it, I just ran a clean installation using a container with the same specs, maybe it has to be with Ruby?

**Comment by tiagocassio** [comment] 2019-05-02 19:12
Maybe, i'm working with Ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by kurenn** [comment] 2019-05-06 15:45
Try with tha version as well, could not reproduce it, is the version of rails the only one you are running, have you tried running it with `bundle exec`?

**Comment by tiagocassio** [comment] 2019-05-06 16:46
With the latest stable version (5.2.3) this warning doesn't appears.

**Comment by kurenn** [comment] 2019-06-04 20:19
Nice, so you think we can close this?

**Closed** 2019-10-01 18:04 UTC
